# Change these first
owner: elepallec # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Plex
    url: https://plex.lepallec.tv/web/index.html
  - name: Ombi
    url: https://ombi.lepallec.tv
  - name: Tautulli
    url: https://tautulli.lepallec.tv

status-website:
  cname: uptime.lepallec.tv
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: uptime.lepallec.tv
  introTitle: "Status of **lepallec.tv** services"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
