# Change these first
owner: elepallece # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Plex
    url: https://plex.lepallec.tv
  - name: Ombi
    url: https://ombi.lepallec.tv
  - name: Tautulli
    url: https://tautulli.lepallec.tv

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.lepallec.tv
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Status of *lepallec.tv* services"
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
